The exception generated is IndexError: list index out of range



l=[1,2,3]
try:
    print(l[3])

except IndexError:
    print("index is out of bound")